package model;
// Generated 22.May.2018 00:24:13 by Hibernate Tools 4.3.1


/**
 * Ogretimuyesi generated by hbm2java
 */
public class Ogretimuyesi  implements java.io.Serializable {
     private Integer ogretimuyesiiid;
     private String sicilno;
     private String adsoyad;
     private String sehir;
     private String telno;

    public Ogretimuyesi() {
    }

    public Ogretimuyesi(String sicilno, String adsoyad, String sehir, String telno) {
       this.sicilno = sicilno;
       this.adsoyad = adsoyad;
       this.sehir = sehir;
       this.telno = telno;
    }
   
    public Integer getOgretimuyesiiid() {
        return this.ogretimuyesiiid;
    }
    
    public void setOgretimuyesiiid(Integer ogretimuyesiiid) {
        this.ogretimuyesiiid = ogretimuyesiiid;
    }
    public String getSicilno() {
        return this.sicilno;
    }
    
    public void setSicilno(String sicilno) {
        this.sicilno = sicilno;
    }
    public String getAdsoyad() {
        return this.adsoyad;
    }
    
    public void setAdsoyad(String adsoyad) {
        this.adsoyad = adsoyad;
    }
    public String getSehir() {
        return this.sehir;
    }
    
    public void setSehir(String sehir) {
        this.sehir = sehir;
    }
    public String getTelno() {
        return this.telno;
    }
    
    public void setTelno(String telno) {
        this.telno = telno;
    }
}


